-- Drop the view first (depends on the columns being removed), then the
-- flat price_min/price_max columns from Phase 8's first pass.
drop view if exists public.gym_price_tiers;
alter table public.gyms drop column if exists price_min;
alter table public.gyms drop column if exists price_max;

-- ============================================================
-- gym_pricing_plans - multiple plan options per gym, each normalized to a
-- monthly-equivalent rate for fair comparison regardless of billing period.
-- ============================================================
create table public.gym_pricing_plans (
  id bigint generated by default as identity primary key,
  gym_id bigint not null references public.gyms(id),
  plan_type text not null check (plan_type in ('monthly', 'quarterly', 'half_yearly', 'annual')),
  price numeric not null check (price >= 0),
  monthly_equivalent numeric generated always as (
    price / (case plan_type
      when 'monthly' then 1
      when 'quarterly' then 3
      when 'half_yearly' then 6
      when 'annual' then 12
    end)::numeric
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gym_pricing_plans_unique_type_per_gym unique (gym_id, plan_type)
);

alter table public.gym_pricing_plans enable row level security;

-- Same pattern as gym_equipment/gym_amenities: public read, gym owner/admin
-- staff manage their own gym's rows (is_gym_admin already exists).
create policy "Anyone can view gym pricing plans"
on public.gym_pricing_plans for select
using (true);

create policy "Gym admins can manage gym pricing plans"
on public.gym_pricing_plans for all
using (is_gym_admin(gym_id))
with check (is_gym_admin(gym_id));

grant select on public.gym_pricing_plans to anon;
grant select, insert, update, delete on public.gym_pricing_plans to authenticated;

-- ============================================================
-- gym_price_tiers - same NTILE(3)-per-city shape as before, now driven by
-- each gym's LOWEST monthly_equivalent across its plans (the best deal a
-- member could actually get there), not a flat price_min/price_max.
-- ============================================================
create view public.gym_price_tiers as
with resolved as (
  select
    g.id as gym_id,
    ci.id as city_id,
    (
      select min(pp.monthly_equivalent)
      from public.gym_pricing_plans pp
      where pp.gym_id = g.id
    ) as lowest_monthly_equivalent
  from public.gyms g
  left join public.gym_locations gl on gl.gym_id = g.id and gl.is_primary = true
  left join public.localities loc on loc.id = gl.locality_id
  left join public.cities ci on ci.id = loc.city_id
  where g.status = 'active'
),
tiered as (
  select
    gym_id,
    ntile(3) over (partition by city_id order by lowest_monthly_equivalent) as tier_number
  from resolved
  where city_id is not null and lowest_monthly_equivalent is not null
)
select
  resolved.gym_id,
  resolved.city_id,
  resolved.lowest_monthly_equivalent,
  case tiered.tier_number
    when 1 then 'budget'
    when 2 then 'mid'
    when 3 then 'premium'
    else null
  end as price_tier
from resolved
left join tiered on tiered.gym_id = resolved.gym_id;

grant select on public.gym_price_tiers to anon, authenticated;
