-- ============================================================
-- contest_periods
-- ============================================================
-- level is constrained to 'gym' only for now; Phase 7 (City-level contests)
-- will widen this check to include 'city'.
create table public.contest_periods (
  id bigint generated by default as identity primary key,
  level text not null default 'gym' check (level = 'gym'),
  gym_id bigint not null references public.gyms(id),
  gender text not null check (gender in ('male', 'female')),
  nomination_start timestamptz not null,
  nomination_end timestamptz not null,
  voting_start timestamptz not null,
  voting_end timestamptz not null,
  status text not null default 'nominating' check (status in ('nominating', 'voting', 'runoff', 'completed')),
  winner_id bigint,
  parent_contest_period_id bigint references public.contest_periods(id),
  created_at timestamptz not null default now()
);
-- winner_id -> nominations(id) is added after nominations exists below,
-- since the two tables reference each other.

alter table public.contest_periods enable row level security;

create policy "Anyone can view contest periods"
on public.contest_periods
for select
using (true);

grant select on public.contest_periods to anon, authenticated;
-- Deliberately no insert/update/delete grant for anon/authenticated:
-- contest_periods are created and resolved manually via direct DB access
-- (see resolve_gym_contest below), matching the manual gym-onboarding
-- review pattern. SECURITY DEFINER functions still write to this table
-- because they run as the function owner, which isn't subject to this grant.

-- ============================================================
-- nominations
-- ============================================================
create table public.nominations (
  id bigint generated by default as identity primary key,
  contest_period_id bigint not null references public.contest_periods(id),
  user_id uuid not null references auth.users(id),
  primary_photo_url text not null,
  extra_photo_urls text[] not null default '{}',
  status text not null default 'active' check (status in ('active', 'withdrawn')),
  consent_accepted_at timestamptz not null,
  entry_time timestamptz not null default now(),
  rank integer,
  constraint nominations_extra_photos_max_3 check (
    extra_photo_urls is null or array_length(extra_photo_urls, 1) is null or array_length(extra_photo_urls, 1) <= 3
  ),
  constraint nominations_unique_per_contest unique (contest_period_id, user_id)
);

create index nominations_contest_period_id_idx on public.nominations (contest_period_id);

alter table public.nominations enable row level security;

alter table public.contest_periods
  add constraint contest_periods_winner_id_fkey
  foreign key (winner_id) references public.nominations(id) on delete set null;

-- Nomination gate: adult, profile gender matches the contest's gender, and
-- the contest must currently be accepting nominations. "Trusted internal
-- write" bypass exists only for resolve_gym_contest copying tied nominees
-- into a runoff contest (status 'runoff', never reachable by a normal
-- client-initiated nomination since the app only shows the nominate flow
-- while status = 'nominating') - the flag is a transaction-local Postgres
-- GUC that clients can never set themselves (not exposed via any RPC).
create or replace function public.enforce_nomination_rules()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_contest public.contest_periods%rowtype;
  v_profile_gender text;
begin
  if current_setting('app.internal_write', true) = 'true' then
    return new;
  end if;

  if not public.is_adult(new.user_id) then
    raise exception 'You must be an adult to be nominated for Face of the Gym.';
  end if;

  select * into v_contest from public.contest_periods where id = new.contest_period_id;
  if v_contest is null then
    raise exception 'Contest not found.';
  end if;

  if v_contest.status <> 'nominating' then
    raise exception 'Nominations are not currently open for this contest.';
  end if;

  select gender into v_profile_gender from public.profiles where id = new.user_id;
  if v_profile_gender is null or v_profile_gender <> v_contest.gender then
    raise exception 'Your profile gender must match this contest category to be nominated.';
  end if;

  return new;
end;
$function$;

create trigger trg_enforce_nomination_rules
  before insert on public.nominations
  for each row
  execute function public.enforce_nomination_rules();

create policy "Anyone can view nominations"
on public.nominations
for select
using (true);

create policy "Users can nominate themselves"
on public.nominations
for insert
with check (user_id = auth.uid());

revoke update on public.nominations from authenticated;
grant update (status) on public.nominations to authenticated;

create policy "Nominee can withdraw their own nomination"
on public.nominations
for update
using (user_id = auth.uid() and status = 'active')
with check (user_id = auth.uid() and status = 'withdrawn');

grant select, insert on public.nominations to anon, authenticated;
