-- Fix: INSERT should never have been granted to anon (RLS already blocks it
-- since auth.uid() is null for anon, but least-privilege says don't grant
-- what's never usable).
revoke insert on public.nominations from anon;

-- ============================================================
-- votes
-- ============================================================
create table public.votes (
  id bigint generated by default as identity primary key,
  contest_period_id bigint not null references public.contest_periods(id),
  nominee_id bigint not null references public.nominations(id),
  voter_id uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint votes_unique_voter_per_contest unique (contest_period_id, voter_id)
);

create index votes_contest_period_id_idx on public.votes (contest_period_id);
create index votes_nominee_id_idx on public.votes (nominee_id);

alter table public.votes enable row level security;

create or replace function public.enforce_vote_rules()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_contest public.contest_periods%rowtype;
  v_nomination public.nominations%rowtype;
  v_has_valid_checkin boolean;
begin
  select * into v_contest from public.contest_periods where id = new.contest_period_id;
  if v_contest is null then
    raise exception 'Contest not found.';
  end if;

  if v_contest.status <> 'voting' then
    raise exception 'Voting is not currently open for this contest.';
  end if;

  select * into v_nomination from public.nominations where id = new.nominee_id;
  if v_nomination is null or v_nomination.contest_period_id <> new.contest_period_id then
    raise exception 'This nominee is not part of this contest.';
  end if;

  if v_nomination.status <> 'active' then
    raise exception 'This nominee has withdrawn and can no longer receive votes.';
  end if;

  select exists (
    select 1 from public.gym_checkins c
    where c.user_id = new.voter_id and c.gym_id = v_contest.gym_id and c.is_valid = true
  ) into v_has_valid_checkin;

  if not v_has_valid_checkin then
    raise exception 'You need a verified check-in at this gym to vote in its contest.';
  end if;

  return new;
end;
$function$;

create trigger trg_enforce_vote_rules
  before insert on public.votes
  for each row
  execute function public.enforce_vote_rules();

-- Secret ballot: a voter can see their own vote (to render "you voted" in
-- the UI), but not anyone else's, and nobody can see aggregate tallies
-- during active voting - only the final winner is exposed, via
-- contest_periods.winner_id once status = 'completed'.
create policy "Voter can view their own vote"
on public.votes
for select
using (voter_id = auth.uid());

create policy "Users can cast their own vote"
on public.votes
for insert
with check (voter_id = auth.uid());

grant select, insert on public.votes to authenticated;
