-- ============================================================
-- message_threads
-- ============================================================
create table public.message_threads (
  id bigint generated by default as identity primary key,
  user_a uuid not null references auth.users(id),
  user_b uuid not null references auth.users(id),
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  initiated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  report_reason text,
  reported_at timestamptz,
  constraint message_threads_not_self check (user_a <> user_b),
  constraint message_threads_ordered check (user_a < user_b),
  constraint message_threads_initiator_is_participant
    check (initiated_by = user_a or initiated_by = user_b),
  constraint message_threads_unique_pair unique (user_a, user_b)
);

alter table public.message_threads enable row level security;

-- Normalizes (user_a, user_b) into canonical order regardless of what the
-- client passes, and age-gates thread creation - this is the enforcement
-- point for "minors fully excluded from messaging" at creation time.
create or replace function public.enforce_message_thread_rules()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_a uuid;
  v_b uuid;
begin
  if new.user_a = new.user_b then
    raise exception 'You cannot start a conversation with yourself.';
  end if;

  v_a := least(new.user_a, new.user_b);
  v_b := greatest(new.user_a, new.user_b);
  new.user_a := v_a;
  new.user_b := v_b;

  if not public.is_adult(new.user_a) or not public.is_adult(new.user_b) then
    raise exception 'Messaging is only available between adults.';
  end if;

  return new;
end;
$function$;

create trigger trg_enforce_message_thread_rules
  before insert on public.message_threads
  for each row
  execute function public.enforce_message_thread_rules();

create policy "Participants can view their threads"
on public.message_threads
for select
using (auth.uid() = user_a or auth.uid() = user_b);

create policy "Users can start a thread they participate in"
on public.message_threads
for insert
with check (
  initiated_by = auth.uid()
  and (auth.uid() = user_a or auth.uid() = user_b)
);

-- Column-level grant restricts which fields authenticated users may ever
-- touch via UPDATE; the row-level policy below then restricts WHO and WHEN.
-- Together: only the recipient, only while still pending, may accept
-- (status -> 'accepted') or report (report_reason/reported_at) a thread -
-- matching item 4's "report option on a pending thread" scope exactly.
revoke update on public.message_threads from authenticated;
grant update (status, report_reason, reported_at) on public.message_threads to authenticated;

create policy "Recipient can accept or report a pending thread"
on public.message_threads
for update
using (
  status = 'pending'
  and auth.uid() <> initiated_by
  and (auth.uid() = user_a or auth.uid() = user_b)
)
with check (
  auth.uid() <> initiated_by
  and (auth.uid() = user_a or auth.uid() = user_b)
);

-- Only the recipient (never the initiator) may delete a thread, in any
-- status - this is the "decline a request" / "delete a conversation" action.
create policy "Recipient can delete the thread"
on public.message_threads
for delete
using (
  auth.uid() <> initiated_by
  and (auth.uid() = user_a or auth.uid() = user_b)
);

-- ============================================================
-- messages
-- ============================================================
create table public.messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.message_threads(id) on delete cascade,
  sender_id uuid not null references auth.users(id),
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now()
);

create index messages_thread_id_created_at_idx on public.messages (thread_id, created_at);

alter table public.messages enable row level security;

-- Design decision (see chat response): the INITIATOR may send at any time,
-- pending or accepted. The RECIPIENT may only send once the thread is
-- 'accepted' - they must consent before participating. Also re-checks
-- is_adult() on every send (not just thread creation), since DOB can still
-- be edited up to twice post-signup - a participant who edits their way
-- into being a minor loses messaging access immediately, not just for new
-- threads.
create or replace function public.enforce_message_send_rules()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_thread public.message_threads%rowtype;
begin
  select * into v_thread from public.message_threads where id = new.thread_id;

  if v_thread is null then
    raise exception 'Thread not found.';
  end if;

  if new.sender_id <> v_thread.user_a and new.sender_id <> v_thread.user_b then
    raise exception 'You are not a participant in this conversation.';
  end if;

  if v_thread.status = 'pending' and new.sender_id <> v_thread.initiated_by then
    raise exception 'You can reply once this message request is accepted.';
  end if;

  if not public.is_adult(v_thread.user_a) or not public.is_adult(v_thread.user_b) then
    raise exception 'Messaging is only available between adults.';
  end if;

  return new;
end;
$function$;

create trigger trg_enforce_message_send_rules
  before insert on public.messages
  for each row
  execute function public.enforce_message_send_rules();

create policy "Participants can view thread messages"
on public.messages
for select
using (
  exists (
    select 1 from public.message_threads t
    where t.id = messages.thread_id
      and (t.user_a = auth.uid() or t.user_b = auth.uid())
  )
);

create policy "Participants can send messages"
on public.messages
for insert
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.message_threads t
    where t.id = messages.thread_id
      and (t.user_a = auth.uid() or t.user_b = auth.uid())
  )
);
