-- Traces a city-level nomination back to the gym-level nomination it was
-- auto-populated from (via populate_city_bracket). Null for gym-level
-- nominations and for any hypothetical directly-entered city nomination.
alter table public.nominations add column source_nomination_id bigint references public.nominations(id);

-- ============================================================
-- bracket_rounds
-- ============================================================
create table public.bracket_rounds (
  id bigint generated by default as identity primary key,
  contest_period_id bigint not null references public.contest_periods(id),
  round_number integer not null,
  voting_start timestamptz not null,
  voting_end timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'voting', 'completed')),
  created_at timestamptz not null default now(),
  unique (contest_period_id, round_number)
);

alter table public.bracket_rounds enable row level security;

create or replace function public.enforce_bracket_round_is_city_level()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not exists (
    select 1 from public.contest_periods cp
    where cp.id = new.contest_period_id and cp.level = 'city'
  ) then
    raise exception 'Bracket rounds can only belong to a city-level contest period.';
  end if;
  return new;
end;
$function$;

create trigger trg_enforce_bracket_round_is_city_level
  before insert on public.bracket_rounds
  for each row
  execute function public.enforce_bracket_round_is_city_level();

create policy "Anyone can view bracket rounds"
on public.bracket_rounds for select using (true);

grant select on public.bracket_rounds to anon, authenticated;

-- ============================================================
-- bracket_matchups
-- ============================================================
create table public.bracket_matchups (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.bracket_rounds(id),
  nominee_a_id bigint references public.nominations(id),
  nominee_b_id bigint references public.nominations(id),
  winner_id bigint references public.nominations(id),
  status text not null default 'pending' check (status in ('pending', 'voting', 'completed')),
  created_at timestamptz not null default now(),
  constraint bracket_matchups_not_both_null check (nominee_a_id is not null or nominee_b_id is not null),
  constraint bracket_matchups_distinct_sides check (
    nominee_a_id is null or nominee_b_id is null or nominee_a_id <> nominee_b_id
  )
);

create index bracket_matchups_round_id_idx on public.bracket_matchups (round_id);

alter table public.bracket_matchups enable row level security;

create policy "Anyone can view bracket matchups"
on public.bracket_matchups for select using (true);

grant select on public.bracket_matchups to anon, authenticated;

-- ============================================================
-- bracket_votes
-- ============================================================
create table public.bracket_votes (
  id bigint generated by default as identity primary key,
  matchup_id bigint not null references public.bracket_matchups(id),
  voter_id uuid not null references auth.users(id),
  nominee_id bigint not null references public.nominations(id),
  created_at timestamptz not null default now(),
  constraint bracket_votes_unique_voter_per_matchup unique (matchup_id, voter_id)
);

create index bracket_votes_matchup_id_idx on public.bracket_votes (matchup_id);

alter table public.bracket_votes enable row level security;

-- A voter is eligible for a city-level matchup if they have a verified
-- check-in at ANY gym whose primary location resolves to this contest's
-- city - same gym_locations -> localities -> cities join used by
-- search_gyms.
create or replace function public.enforce_bracket_vote_rules()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_matchup public.bracket_matchups%rowtype;
  v_round public.bracket_rounds%rowtype;
  v_contest public.contest_periods%rowtype;
  v_has_valid_checkin boolean;
begin
  select * into v_matchup from public.bracket_matchups where id = new.matchup_id;
  if v_matchup is null then
    raise exception 'Matchup not found.';
  end if;

  if v_matchup.status <> 'voting' then
    raise exception 'Voting is not currently open for this matchup.';
  end if;

  if new.nominee_id <> v_matchup.nominee_a_id and new.nominee_id <> v_matchup.nominee_b_id then
    raise exception 'This nominee is not part of this matchup.';
  end if;

  select * into v_round from public.bracket_rounds where id = v_matchup.round_id;
  select * into v_contest from public.contest_periods where id = v_round.contest_period_id;

  select exists (
    select 1
    from public.gym_checkins c
    join public.gym_locations gl on gl.gym_id = c.gym_id and gl.is_primary = true
    join public.localities loc on loc.id = gl.locality_id
    join public.cities ci on ci.id = loc.city_id
    where c.user_id = new.voter_id
      and c.is_valid = true
      and ci.id = v_contest.city_id
  ) into v_has_valid_checkin;

  if not v_has_valid_checkin then
    raise exception 'You need a verified check-in at a gym in this city to vote in this contest.';
  end if;

  return new;
end;
$function$;

create trigger trg_enforce_bracket_vote_rules
  before insert on public.bracket_votes
  for each row
  execute function public.enforce_bracket_vote_rules();

-- Secret ballot, same as gym-level votes: a voter sees only their own vote.
create policy "Voter can view their own bracket vote"
on public.bracket_votes for select
using (voter_id = auth.uid());

create policy "Users can cast their own bracket vote"
on public.bracket_votes for insert
with check (voter_id = auth.uid());

grant select, insert on public.bracket_votes to authenticated;
